### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by Alvie** [lmaucoin/friendship-ended#5]
Probably not an issue with the code itself but the demo site on http://friendship.leigh.cool/ is down:

![Screenshot_20211124-124017](https://user-images.githubusercontent.com/8447791/143240273-fde37c03-98ba-4b40-951c-b8cae6d0b275.png)

**Comment by lmaucoin** [comment]
Thanks! It was a DNS issue. It's fixed!

**Comment by Alvie** [comment]
Awesome thanks!
![image](https://user-images.githubusercontent.com/8447791/145511683-89b7a6d6-5adb-4bab-914b-3533fb478fb6.png)
